/**
 * Downloads the three Google Fonts families into public/fonts/ and writes
 * src/fonts.css with matching @font-face rules.
 *
 * Loading these from fonts.googleapis.com costs a render-blocking stylesheet on
 * a third-party origin (~300 ms) plus DNS + TLS to a second origin
 * (fonts.gstatic.com) before a single glyph arrives. Self-hosting turns that
 * into same-origin requests the browser can start immediately.
 *
 * Re-run only when the families or weights change:
 *   node scripts/fetch-fonts.mjs
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'public/fonts')

// Must match the families/axes the app actually uses (see --font-* in index.css).
// All three are variable fonts, so the weights are requested as *ranges*
// (300..700) rather than a list (300;400;500…). A list makes the API emit one
// @font-face per weight, each pointing at the same variable file — five
// identical 61 KiB downloads for DM Sans alone. One range = one file that
// covers every weight in it.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=DM+Sans:opsz,wght@9..40,300..700' +
  '&family=Space+Grotesk:wght@400..700' +
  '&family=JetBrains+Mono:wght@400..500' +
  '&display=swap'

// A modern desktop UA makes the API serve woff2 + unicode-range subsets.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

// Latin only: the UI is English, and pulling cyrillic/greek would triple the
// byte count for glyphs nobody renders.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then(r => {
  if (!r.ok) throw new Error(`Google Fonts CSS failed: ${r.status}`)
  return r.text()
})

// Start from a clean directory so a changed weight list can't leave orphaned
// files behind that still get precached by the service worker.
rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

// Guards against the same remote file being written under two names.
const seen = new Map()

// Google emits `/* subset */` comments before each @font-face block.
const blocks = css.split(/\/\*\s*([\w\-[\]]+)\s*\*\//).slice(1)
const rules = []
let downloaded = 0

for (let i = 0; i < blocks.length; i += 2) {
  const subset = blocks[i]
  const block = blocks[i + 1]
  if (!KEEP_SUBSETS.has(subset)) continue

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim()
  const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? 'normal'
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
  if (!url || !family || !weight) continue

  let name = seen.get(url)
  if (!name) {
    name = `${family.replace(/\s+/g, '-')}-${weight.replace(/\s+/g, '_')}-${subset}.woff2`
    const bytes = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then(r => {
      if (!r.ok) throw new Error(`font download failed: ${url} → ${r.status}`)
      return r.arrayBuffer()
    }))
    writeFileSync(resolve(outDir, name), bytes)
    seen.set(url, name)
    downloaded++
    console.log(`  ${name} (${(bytes.length / 1024).toFixed(1)} KiB)`)
  }

  rules.push(
    [
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      // swap keeps text visible during the (now same-origin, very short) load.
      '  font-display: swap;',
      `  src: url('/fonts/${name}') format('woff2');`,
      range ? `  unicode-range: ${range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  )
}

if (rules.length === 0) throw new Error('No @font-face rules produced — the CSS format may have changed.')

writeFileSync(
  resolve(root, 'src/fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Self-hosted copies of the Google Fonts families used by the UI, so the\n` +
    `   first paint doesn't wait on a third-party stylesheet. */\n\n` +
    `${rules.join('\n\n')}\n`,
)

console.log(`\n✓ ${downloaded} font files → public/fonts/`)
console.log(`✓ ${rules.length} @font-face rules → src/fonts.css`)
